apiVersion: v1
kind: Service
metadata:
  name: beacon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: beacon
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
